import { Inter } from "next/font/google";
import Header from "./componentes/Header";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="bg-zinc-950 text-white leading-loose">
      <body className={inter.className}>
        <Header/>
        {children}
      </body>
    </html>
  );
}
